language: ruby

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle install
  - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $SECRET_TOKEN  # GitHub Personal Access Token을 환경 변수로 설정
  local_dir: _site  # Jekyll이 생성한 빌드 디렉토리
  on:
    branch: main  # GitHub Pages로 배포할 브랜치

rvm:
 - 3.3.6